### ISSUE TITLE
vis_dat(diamonds) shows an empty plot (only light gray lines are visible)

### ISSUE THREAD

**Issue by sfd99** [ropensci/visdat#132] opened 2020-12-16 18:22 UTC
_**Hi**_, 
_always_ loved using **VISDAT**.

But now:
  vis_dat(diamonds)
shows an empty **visdat** plot! 
(only a tenuous grid w/ light gray lines is visible...no colors).

   vis_dat(iris)
   vis_dat(airquality) 
are _both_ OK!.

Issue looks identical to Issue #32:
"Blank plot with grid lines shown #32"

UPDATE:
Downsampled 
the number of rows in diamonds
and **visdat** works ok:

diamonds %>%
  slice(1:1000) %>%
  vis_dat()

Suggestion: 
would be VERY nice 
if **visdat** would "downsample" / "slice" 
the number of rows of a _large_ DF
_automatically_.

This would avoid presenting the (startled) user
an empty plot,
w/o any warning...

Just a suggestion 
of a _long-time fan_ of **VISDAT**! :-)

**SFd99**
_latest versions of:_
**visdat** pkg 0.6.0.9000 (installed via devtools)
**Ubuntu Linux 20.04 64bits**
**R 4.0.3**
**Rstudio** 1.3.1073
---

**Comment by njtierney** [comment] 2022-02-16 01:14
Hi there! This is a duplicate of #32 - unfortunately it is a bit tricky to solve!

**Closed by njtierney** 2022-02-16 01:14 UTC
